language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - 1_monolith_with_tests

script:
  - cd library-monolith
  - ./gradlew check

before_cache:
  - rm -f  $HOME/library-monolith/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/library-monolith/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/library-monolith/.gradle/caches/
    - $HOME/library-monolith/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
